name: Tranform Tokens

on:
  push:
    paths:
      - 'src/tokens/**'
    branches:
      - master

jobs:
  transform_tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: LICENSE_KEY=${{ secrets.LICENSE_KEY }} LICENSE_EMAIL=${{ secrets.LICENSE_EMAIL }} npx figma-tokens-transformer transform

      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.COMMIT_TOKEN }}
          script: |
            git config --global user.email "mmuzzamil90@gmail.com"
            git config --global user.name "muzzamilr"
            git add .
            git commit -m "Generated new token files"
            git push
